/* eslint-disable jsx-a11y/no-noninteractive-tabindex, jsx-a11y/no-static-element-interactions, jsx-a11y/no-noninteractive-element-interactions */
"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

const nav = [["01","about","Sobre"],["02","work","Projetos"],["03","stack","Stack"],["04","journey","Trajetória"],["05","contact","Contato"]];
const GITHUB="https://github.com/CodeShinu";
const LINKEDIN="https://www.linkedin.com/in/devkaua06/";
const terminalOutput: Record<string,string[]> = {
  help:["about · projects · skills · contact · clear"],
  about:["Kauã Carlos","Ciência da Computação @ USCS","São Caetano do Sul, SP"],
  projects:["01  ProjetoKC API        WIP","02  Controle de Gastos   CLI"],
  skills:["CORE      Python","BACKEND   Flask · REST","DATA      SQL · JSON","TOOLS     Git · GitHub"],
  contact:["status: open_to_internship","github: /CodeShinu","linkedin: /in/devkaua06"],
  coffee:["☕ input recebido. foco restaurado."],
};

function NetworkCanvas(){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=ref.current, ctx=canvas?.getContext("2d"); if(!canvas||!ctx)return;
    const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;
    let frame=0,w=0,h=0,pointer={x:.68,y:.42};
    const nodes=Array.from({length:17},(_,i)=>({x:((i*47)%91)/100+.04,y:((i*31)%83)/100+.08,phase:i*.7}));
    const resize=()=>{const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(devicePixelRatio,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)};
    const move=(e:PointerEvent)=>{const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}};
    const draw=(time=0)=>{ctx.clearRect(0,0,w,h);const pts=nodes.map(n=>({x:(n.x+(pointer.x-.5)*.018*Math.sin(n.phase))*w,y:(n.y+(pointer.y-.5)*.018*Math.cos(n.phase))*h}));ctx.lineWidth=1;pts.forEach((a,i)=>pts.slice(i+1).forEach(b=>{const d=Math.hypot(a.x-b.x,a.y-b.y),limit=Math.min(w,h)*.27;if(d<limit){ctx.strokeStyle=`rgba(190,255,87,${(1-d/limit)*.18})`;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}));pts.forEach((p,i)=>{ctx.fillStyle=i===7?"#beff57":"rgba(232,236,225,.7)";ctx.beginPath();ctx.arc(p.x,p.y,reduced?2:2+Math.sin(time/700+i)*.6,0,Math.PI*2);ctx.fill()});if(!reduced)frame=requestAnimationFrame(draw)};
    resize();draw();addEventListener("resize",resize);canvas.addEventListener("pointermove",move);
    return()=>{cancelAnimationFrame(frame);removeEventListener("resize",resize);canvas.removeEventListener("pointermove",move)};
  },[]);
  return <canvas ref={ref} className="network" aria-hidden="true"/>;
}

function Terminal(){
  const [history,setHistory]=useState(["System ready. Digite “help”."]),[value,setValue]=useState("");
  const submit=(e:FormEvent)=>{e.preventDefault();const command=value.trim().toLowerCase();if(!command)return;setValue("");if(command==="clear")return setHistory([]);setHistory(h=>[...h,`$ ${command}`,...(terminalOutput[command]??[`comando não encontrado: ${command}`])])};
  return <div className="terminal" aria-label="Terminal interativo controlado"><div className="terminal-bar"><span>kc://local/session</span><span className="status-dot">ONLINE</span></div><div className="terminal-body" aria-live="polite">{history.map((line,i)=><div key={`${line}-${i}`} className={line.startsWith("$")?"command":""}>{line}</div>)}<form onSubmit={submit}><label htmlFor="terminal-input">$</label><input id="terminal-input" value={value} onChange={e=>setValue(e.target.value)} autoComplete="off" spellCheck={false} aria-label="Comando do terminal"/></form></div></div>;
}

export default function Home(){
  const [active,setActive]=useState("about"),[project,setProject]=useState<"api"|"gastos"|null>(null);
  useEffect(()=>{const root=document.documentElement;const pointer=(e:PointerEvent)=>{root.style.setProperty("--mx",`${e.clientX}px`);root.style.setProperty("--my",`${e.clientY}px`)};const sections=[...document.querySelectorAll<HTMLElement>("section[id]")];const io=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){setActive(entry.target.id);entry.target.classList.add("seen")}}),{rootMargin:"-30% 0px -55%"});sections.forEach(s=>io.observe(s));addEventListener("pointermove",pointer,{passive:true});console.info("Você abriu o DevTools. Já gostei de você.");return()=>{io.disconnect();removeEventListener("pointermove",pointer)}},[]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setProject(null)};document.body.style.overflow=project?"hidden":"";addEventListener("keydown",key);return()=>{document.body.style.overflow="";removeEventListener("keydown",key)}},[project]);
  return <>
    <a href="#main" className="skip">Pular para o conteúdo</a>
    <header className="topbar"><a className="mark" href="#top" aria-label="Kauã Carlos, início"><span>KC</span><i/></a><nav aria-label="Navegação principal">{nav.map(([n,id,label])=><a key={id} href={`#${id}`} className={active===id?"active":""}><small>{n}</small>{label}</a>)}</nav><div className="header-actions"><a href={GITHUB} target="_blank" rel="noopener noreferrer" aria-label="GitHub de Kauã Carlos, abre em nova aba">GH ↗</a><a href={LINKEDIN} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn de Kauã Carlos, abre em nova aba">IN ↗</a><span className="availability"><i/> OPEN TO INTERNSHIP</span></div></header>
    <main id="main">
      <section className="hero seen" id="top"><div className="hero-meta mono"><span>23.6208° S / 46.5547° W</span><span>BUILD / LEARN / ITERATE</span></div><div className="hero-copy"><p className="eyebrow">COMPUTER SCIENCE · USCS</p><h1>KAUÃ<br/><span>CARLOS</span></h1><div className="hero-bottom"><div><p className="lead">Aprendendo a construir o que acontece <em>antes da interface.</em></p><div className="hero-actions"><a className="primary-action" href="#work">Explorar projetos <span>↓</span></a><a href={GITHUB} target="_blank" rel="noopener noreferrer">Ver GitHub ↗</a><a href={LINKEDIN} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div></div><div className="focus mono"><span>FOCUS_001</span><strong>PYTHON / BACKEND / DATA</strong><span>SEEKING_002</span><strong>ESTÁGIO EM TECNOLOGIA</strong></div></div></div><div className="hero-system"><NetworkCanvas/><span className="axis x">DATA FLOW →</span><span className="axis y">SYSTEM / 01</span><div className="node-label mono">PROCESSING<br/><b>17 NODES</b></div></div><a className="scroll-cue" href="#about"><span>EXPLORAR</span><i/></a></section>
      <section className="about reveal" id="about"><div className="section-index mono">01 / SOBRE</div><div className="about-main"><p className="kicker">Em construção, de propósito.</p><h2>Estudo Ciência da Computação e uso projetos próprios para entender sistemas na prática.</h2><div className="about-grid"><p>Hoje, meu foco está em Python, backend e dados: construir APIs, organizar informação e descobrir por que as coisas quebram.</p><dl className="facts mono"><div><dt>LOCAL</dt><dd>São Caetano do Sul, SP</dd></div><div><dt>FORMAÇÃO</dt><dd>Ciência da Computação — USCS</dd></div><div><dt>PREVISÃO</dt><dd>2028</dd></div></dl></div></div></section>
      <section className="work reveal" id="work"><div className="section-heading"><div className="section-index mono">02 / PROJETOS</div><h2>Do problema<br/>ao <span>commit.</span></h2><p>Dois projetos, duas maneiras de transformar estudo em algo que funciona.</p></div><div className="project-list">
        <article className="project api-project" tabIndex={0}><div className="project-number mono">01 — WIP</div><div className="project-copy"><p className="mono muted">PYTHON / FLASK / JSON / GIT</p><h3>ProjetoKC API</h3><p>Uma API REST construída para estudar o caminho entre uma requisição e uma resposta.</p><button onClick={()=>setProject("api")}>Abrir estudo do projeto <span>↗</span></button></div><div className="api-visual" aria-label="Representação de fluxo da API"><div className="api-stage"><small>REQUEST</small><b>POST /tasks</b></div><i>→</i><div className="api-core"><span>KC</span><small>API</small></div><i>→</i><div className="api-stage response"><small>RESPONSE</small><b>201 CREATED</b></div><pre>{`{\n  "titulo": "Aprender Flask",\n  "concluida": false\n}`}</pre></div></article>
        <article className="project expense-project" tabIndex={0}><div className="project-number mono">02 — CLI</div><div className="project-copy"><p className="mono muted">PYTHON / JSON / GIT</p><h3>Controle de<br/>Gastos Pessoais</h3><p>Aplicação de terminal para registrar, filtrar, calcular e persistir despesas.</p><button onClick={()=>setProject("gastos")}>Abrir estudo do projeto <span>↗</span></button></div><div className="ledger" aria-hidden="true"><div className="ledger-head"><span>expense.log</span><span>3 entries</span></div>{[["ALIMENTAÇÃO","R$ 42,90"],["TRANSPORTE","R$ 18,50"],["ESTUDOS","R$ 79,00"]].map((x,i)=><div className="ledger-row" key={i}><span>0{i+1}</span><b>{x[0]}</b><em>{x[1]}</em></div>)}<div className="ledger-total"><span>TOTAL</span><b>R$ 140,40</b></div></div></article>
      </div><aside className="code-callout"><div><span className="mono">SOURCE / PUBLIC</span><h3>O código também conta a história.</h3><p>Repositórios, experimentos e a evolução dos projetos ficam disponíveis no GitHub.</p></div><a href={GITHUB} target="_blank" rel="noopener noreferrer">Explorar meu GitHub <span>↗</span></a></aside></section>
      <section className="stack reveal" id="stack"><div className="section-index mono">03 / STACK ATUAL</div><div className="stack-layout"><div><p className="kicker">Ferramentas com contexto.</p><h2>O que estou usando para transformar fundamentos em software.</h2></div><div className="matrix">{[['CORE','Python','linguagem principal'],['BACKEND','Flask · REST','APIs e serviços'],['DATA','SQL · JSON','modelagem e persistência'],['FOUNDATIONS','Java · POO','lógica e estruturas'],['TOOLS','Git · GitHub','versão e colaboração'],['EXPLORING','Testes · Validação','próximos passos']].map(([a,b,c],i)=><div className="matrix-row" key={a}><span className="mono">0{i+1} {a}</span><strong>{b}</strong><small>{c}</small></div>)}</div></div><Terminal/></section>
      <section className="journey reveal" id="journey"><div className="section-index mono">04 / TRAJETÓRIA</div><div className="journey-title"><p className="kicker">Uma linha ainda aberta.</p><h2>Aprender,<br/>aplicar,<br/><span>repetir.</span></h2></div><div className="timeline"><div className="time-item"><time>2023</time><i/><div><b>Web Design Front-end</b><span>SENAI</span></div></div><div className="time-item"><time>2025</time><i/><div><b>Python · SQL · Cibersegurança</b><span>Fundação Bradesco · Cisco</span></div></div><div className="time-item current"><time>2026</time><i/><div><b>Ciência da Computação</b><span>USCS · Backend · APIs · Projetos próprios</span></div></div><div className="time-item now"><time>NOW</time><i/><div><b>Building...</b><span>próximo commit em andamento</span></div></div></div><div className="credentials"><h3>Formação complementar</h3><ul><li><span>FIAP</span>Lógica de Programação, POO e Java</li><li><span>FUNDAÇÃO BRADESCO</span>Modelagem de Dados e SQL</li><li><span>FUNDAÇÃO BRADESCO</span>Python e Estruturas de Dados</li><li><span>CISCO</span>Fundamentos de Cibersegurança</li><li><span>FISK</span>Inglês Intermediário</li></ul></div><div className="experience"><span className="mono">EXPERIÊNCIA / 2025—2026</span><h3>ABCEL Assistência Funeral</h3><p>Jovem Aprendiz · fev/2025 — mai/2026</p><p>Rotinas administrativas, organização de informações, Excel e apoio a processos internos.</p></div></section>
      <section className="contact reveal" id="contact"><div className="contact-grid"><div><div className="section-index mono">05 / CONTATO</div><p className="status-big"><i/> CURRENT STATUS</p><h2>Pronto para o<br/><span>próximo contexto.</span></h2></div><div className="contact-side"><p>Busco uma oportunidade de estágio para aprender com problemas reais e contribuir com o que já sei construir.</p><div className="contact-links"><a href={LINKEDIN} target="_blank" rel="noopener noreferrer"><small>CONEXÃO PROFISSIONAL</small><strong>LinkedIn</strong><span>↗</span></a><a href={GITHUB} target="_blank" rel="noopener noreferrer"><small>CÓDIGO & PROJETOS</small><strong>GitHub</strong><span>↗</span></a></div><div className="contact-state mono"><span>ROLE</span><b>INTERNSHIP</b><span>LOCATION</span><b>SÃO CAETANO DO SUL · SP</b></div></div></div><footer><span>KAUÃ CARLOS © 2026 · BUILDING IN PUBLIC</span><div><a href={GITHUB} target="_blank" rel="noopener noreferrer">GITHUB ↗</a><a href={LINKEDIN} target="_blank" rel="noopener noreferrer">LINKEDIN ↗</a><a href="#top">TOPO ↑</a></div></footer></section>
    </main>
    {project&&<div className="modal-backdrop" onMouseDown={()=>setProject(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setProject(null)} aria-label="Fechar projeto">×</button>{project==="api"?<><p className="mono accent">PROJECT / 01 · WIP</p><h2 id="modal-title">ProjetoKC API</h2><div className="case-grid"><div><small>PROBLEMA</small><p>Entender como um backend recebe dados, processa rotas e devolve respostas HTTP.</p></div><div><small>IDEIA</small><p>Uma API de tarefas pequena o suficiente para aprender cada parte sem esconder a lógica.</p></div><div><small>IMPLEMENTAÇÃO ATUAL</small><p>GET /, GET /tasks e POST /tasks com Python, Flask e JSON.</p></div><div><small>PRÓXIMOS ESTUDOS</small><p>Persistência, outras operações CRUD, validações e testes.</p></div><div><small>STATUS</small><p>Em desenvolvimento. Os próximos passos ainda não foram implementados.</p></div></div></>:<><p className="mono accent">PROJECT / 02 · CLI</p><h2 id="modal-title">Controle de Gastos Pessoais</h2><div className="case-grid"><div><small>PROBLEMA</small><p>Organizar despesas pessoais com uma interface simples de terminal.</p></div><div><small>RECURSOS</small><p>Adicionar, listar, filtrar por categoria, calcular e remover registros.</p></div><div><small>IMPLEMENTAÇÃO</small><p>Aplicação CLI em Python com persistência local em JSON.</p></div><div><small>STACK</small><p>Python · JSON · Git</p></div></div></>}</div></div>}
  </>;
}
